### ISSUE TITLE
Q: Whats the reason behind custom rpc client?

### ISSUE THREAD

**Issue by Wondertan** [celenium-io/celestia-indexer#168]
I was looking through your code and how you interact with nodes, and I wonder why you [handcraft RPC requests](https://github.com/celenium-io/celestia-indexer/blob/98283585062f935cb49a7c3885b47fc97ad7bf9d/pkg/node/dal/blob.go#L21) instead of using the client node has?

**Comment by Wondertan** [comment]
[Option for client](https://github.com/rollkit/celestia-openrpc/)

**Comment by Wondertan** [comment]
You also could reuse the types we define

**Comment by aopoltorzhicky** [comment]
Hi, we use our own API wrapper because your wrapper does not realize a rate limit. It's required because we allow to request any blob by our API and it can be potential weak point.

**Comment by Wondertan** [comment]
Why do you need a client side rate limit? The node could have a rate limit on the server side

**Comment by aopoltorzhicky** [comment]
Almost all services temporarily blocks client which makes too many requests. It would be bad if node blocks our back-end. I don't know the behavior of node so it's easier to limit requests on client side.

**Comment by Wondertan** [comment]
I see. Currently node doesn't have any rate-limiting. It [will have it](https://github.com/celestiaorg/celestia-node/issues/3136) optionally, but not now. Hence you don't really need it to have client side one, as there is nothing blocking for you. Also, the rate-limiting we will do won't be blocking, but slowing request processing. Btw, you ask me anything about the node next time to validate your assumption, I am happy to help you.

**Comment by aopoltorzhicky** [comment]
Got it. Thank you for the information.
